export const DEFAULT_COMMIT_MESSAGE_PROMPT = [
  "Write a Git commit message describing the staged changes.",
  "",
  "Format - follow Conventional Commits: type(scope): subject",
  "- Allowed types: feat, fix, refactor, perf, docs, test, build, ci, chore, revert.",
  "- Use a lowercase type. Set scope to the primary module when one clearly dominates;",
  "  omit the scope and parentheses entirely when no single module does.",
  "- Write the subject in the imperative mood (\"add\", \"fix\", \"remove\"), aim for under",
  "  50 characters, and use no trailing period.",
  "",
  "Body (optional):",
  "- Include a body only when it clarifies important behavior or explains why the change",
  "  was made - do not restate the diff.",
  "- Separate the subject and body with exactly one blank line.",
  "- Use '-' bullets; keep each bullet on a single line.",
  "- For a breaking change, append '!' after the type/scope and add a 'BREAKING CHANGE:'",
  "  footer describing the impact.",
  "",
  "Output rules:",
  "- Output only the commit message - no commentary before or after, and no surrounding",
  "  code fences or backticks.",
  "- Do not insert manual line breaks within the subject or within any bullet.",
  "",
  "Example:",
  "feat(inventory): add stack-splitting for equippable items",
  "",
  "- support shift-drag to split a stack across two slots",
  "- clamp the split amount to the source stack size"
].join("\n");
