export const DEFAULT_COMMIT_MESSAGE_PROMPT = [
  "Write one Git commit message that accurately describes the currently staged changes.",
  "",
  "Before writing:",
  "- Inspect only the staged changes, using `git diff --cached` and related read-only commands as needed.",
  "- Ignore unstaged and untracked changes.",
  "- Do not modify files, the index, or the repository.",
  "- Base the message only on evidence visible in the staged diff. Do not invent intent, behavior, issue numbers, or implementation details.",
  "",
  "Commit format:",
  "type(scope): subject",
  "",
  "Use `type: subject` when no single scope clearly represents most of the change.",
  "",
  "Allowed types:",
  "- feat: add or expand user-facing functionality",
  "- fix: correct defective behavior",
  "- refactor: restructure code without intentionally changing behavior",
  "- perf: improve performance",
  "- docs: change documentation only",
  "- test: add or modify tests",
  "- build: change build tooling, dependencies, or packaging",
  "- ci: change continuous-integration configuration",
  "- chore: perform maintenance not covered by another type",
  "- revert: revert a previous change",
  "",
  "Selection rules:",
  "- Choose the type that best represents the primary purpose of the staged changes.",
  "- Prefer `fix` over `refactor` when the change corrects a defect.",
  "- Prefer `feat` when the change introduces new externally observable behavior.",
  "- Use the primary module, subsystem, package, or feature as the scope when one clearly dominates.",
  "- Keep the scope concise, lowercase, and consistent with names already used in the repository.",
  "- Omit the scope entirely when the changes span multiple areas without a clear primary module.",
  "",
  "Subject rules:",
  "- Write the subject in the imperative mood, such as `add`, `fix`, `remove`, or `update`.",
  "- Start with a lowercase letter.",
  "- Describe the outcome of the change rather than the editing activity.",
  "- Target fewer than 50 characters.",
  "- Do not end with a period.",
  "- Do not place a manual line break within the subject.",
  "",
  "Body:",
  "- Include a body only when it explains important behavior, motivation, constraints, or multiple meaningful aspects that are not clear from the subject.",
  "- Do not merely restate filenames or mechanically summarize the diff.",
  "- Separate the subject and body with exactly one blank line.",
  "- Format each body entry as a `-` bullet.",
  "- Keep each bullet on one physical line.",
  "- Do not include an empty body.",
  "",
  "Breaking changes:",
  "- When the staged changes introduce a breaking change, append `!` after the type or scope:",
  "  - `feat!: ...`",
  "  - `feat(api)!: ...`",
  "- Add a footer after the body, separated by one blank line:",
  "  `BREAKING CHANGE: describe what changed and what consumers must update`",
  "- Do not mark a change as breaking unless the staged diff provides clear evidence.",
  "",
  "Output requirements:",
  "- Output only the completed commit message.",
  "- Do not include commentary, analysis, labels, alternatives, code fences, or backticks.",
  "- Produce exactly one commit message.",
  "",
  "Example:",
  "",
  "feat(inventory): add stack splitting",
  "",
  "- support shift-dragging items between inventory slots",
  "- clamp the split amount to the available stack size"
].join("\n");
