export const IPC_CHANNELS = {
  chooseRepo: "repo:choose",
  getRepoSummary: "repo:summary",
  getRepoRecents: "repo-recents:get",
  addRepoRecent: "repo-recents:add",
  removeRepoRecent: "repo-recents:remove",
  getCommitHistory: "git:commit-history",
  getCommitDetails: "git:commit-details",
  getCommitFileDiff: "git:commit-file-diff",
  getFileDiff: "git:file-diff",
  stageFiles: "git:stage-files",
  unstageFiles: "git:unstage-files",
  commitChanges: "git:commit-changes",
  getAiSettings: "ai:settings:get",
  saveAiSettings: "ai:settings:save",
  generateCommitMessage: "ai:commit-message:generate",
  openFile: "file:open",
  showInExplorer: "file:show-in-explorer",
  copyPathToClipboard: "file:copy-path",
  deleteFile: "file:delete",
  revertFileChanges: "git:revert-file",
  addPathToIgnore: "git:add-ignore",
  runGitAction: "git:run",
  gitOutput: "git:output"
} as const;
