export const DEFAULT_PR_DESCRIPTION_PROMPT = [
  "Write a GitHub pull request description for the changes introduced by the current branch.",
  "",
  "Before writing:",
  "- Compare the current branch against its target branch using the merge-base diff.",
  "- Use the pull request base branch when available; otherwise use the repository's default branch.",
  "- Review the actual diff and relevant commit history. Do not rely on commit messages alone.",
  "- Ignore unrelated working-tree changes that are not part of the branch comparison.",
  "- Base every claim on evidence from the branch changes.",
  "- Do not invent motivation, behavior, issue references, test results, or implementation details.",
  "- When the reason for a change is not evident, describe its purpose or effect without speculating.",
  "",
  "Required structure:",
  "",
  "Opening summary:",
  "- Start with one short paragraph explaining what the pull request changes and, when supported by the available context, why.",
  "- Focus on the overall outcome rather than implementation details.",
  "- Do not add a heading above this paragraph.",
  "",
  "## Changes",
  "- Use `-` bullets to describe the notable changes.",
  "- Group closely related work into concise, outcome-focused bullets.",
  "- Prioritize behavior, architecture, configuration, data, and developer-workflow changes that reviewers need to understand.",
  "- Mention migrations, compatibility implications, new dependencies, or breaking behavior when applicable.",
  "- Do not list every changed file or restate the diff line by line.",
  "- Do not include trivial implementation details unless they materially affect review.",
  "",
  "## Testing",
  "- Briefly describe tests or validation that were actually performed when that information is available.",
  "- Never claim that tests passed or were run without supporting evidence.",
  "- When testing was not performed, state that clearly and list only the most relevant recommended verification steps.",
  "- Distinguish between completed testing and recommended testing.",
  "- Keep this section concise and specific to the changes.",
  "",
  "Output requirements:",
  "- Use GitHub-flavored Markdown.",
  "- Output only the pull request description.",
  "- Do not include a pull request title.",
  "- Do not include commentary, analysis, placeholders, code fences, or backticks.",
  "- Always include the opening summary, `## Changes`, and `## Testing` sections."
].join("\n");
