import type { GitService } from "./gitService";

/**
 * The version-control operations Githead routes per repository. Defined as a
 * `Pick` of the reference `GitService` implementation so the contract can never
 * drift from Git's real method signatures: any new backend (e.g. `LoreService`)
 * that `implements VcsService` is forced to match them exactly.
 *
 * Methods listed here that a backend cannot support (e.g. hunk staging or tags
 * on Lore) must still be implemented, returning a structured "not supported"
 * failure. The renderer normally hides them via {@link RepoCapabilities}.
 */
export type VcsService = Pick<
  GitService,
  | "getRepoSummary"
  | "getRepoIdentity"
  | "getRepoStatus"
  | "getRepoMetadata"
  | "getRepositoryOperationState"
  | "resolveRepositoryOperation"
  | "getConflictResolution"
  | "saveConflictResolution"
  | "getRepoSyncStatus"
  | "getRepoSyncStatuses"
  | "getWorktrees"
  | "getGitHubRepository"
  | "checkRepositoryAccess"
  | "cloneRepository"
  | "getFileDiff"
  | "getStashes"
  | "getStashDetails"
  | "getStashFileDiff"
  | "getStashDiff"
  | "getFilePreview"
  | "fetchLfsImageVersions"
  | "getStagedDiff"
  | "getCommitHistory"
  | "getCommitDetails"
  | "getCommitFileDiff"
  | "getFileHistory"
  | "getFileBlame"
  | "writeCommitFileVersionToPath"
  | "resetFilesToCommit"
  | "stageFiles"
  | "unstageFiles"
  | "stageHunk"
  | "unstageHunk"
  | "commitChanges"
  | "createStash"
  | "applyStash"
  | "popStash"
  | "dropStash"
  | "createBranchFromStash"
  | "resetBranchToCommit"
  | "revertCommit"
  | "createTag"
  | "deleteTag"
  | "switchBranch"
  | "checkoutRemoteBranch"
  | "checkoutGitHubPullRequest"
  | "createBranch"
  | "renameBranch"
  | "deleteBranch"
  | "createWorktree"
  | "checkWorktreeRemoval"
  | "removeWorktree"
  | "setBranchUpstream"
  | "publishBranch"
  | "getPullRecovery"
  | "resolvePullRecovery"
  | "getRemoteConfigs"
  | "addRemote"
  | "renameRemote"
  | "setRemoteUrl"
  | "removeRemote"
  | "revertFileChanges"
  | "addPathToIgnore"
  | "addSafeDirectory"
  | "runGitAction"
  | "runConfiguredAction"
  | "saveConfiguredActions"
>;
